config/routes.rb
Rails.application.routes.draw do
  if RouteTranslator.config.force_locale
    root as: "root_without_locale", to: "application#root_without_locale"
    get "admin(/*admin_path)", to: redirect{|params| "/#{ I18n.default_locale}/admin/#{params[:admin_path]}"}
  end

  mount Cms::Engine => '/'

  mount Ckeditor::Engine => '/ckeditor'

  localized do
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    devise_for :users, module: "users", path: "", path_names: {
        sign_in: "login",
        sign_out: 'logout',
    }

    controller "forms" do
      post "contact_request"
    end

    controller :pages do
      root action: :index
      get "about_us"
      get "contacts"

    end

    resources :articles, only: [:index, :show]
    #get 'pasha', to: 'pasha#cmd'
    get 'about' => 'page#about'
    post 'contact' => 'contact#create', :as => 'contact_create'

    # new catalog
    controller "catalog" do
      get 'catalog', action: 'index', :as => 'catalog'
      get ":id", action: 'node', as: :node
      get ':id', action: 'category', :as => 'category'
      get ':id', action: 'subcategory', :as => 'subcategory'
      get ':id', action: 'brand', :as => 'brand'
      get ':id', action: 'product', :as => 'product'
      post ":id/order", action: 'order', as: 'order'
    end

    get 'unsupported' => 'page#unsupported', :as => 'unsupported'


    match "*url", to: "application#render_not_found", via: :all
  end
end

app/views/partials/_article_banner.html.slim
#article-banner-wrapper
  #slider.sl-slider-wrapper.demo2
    .sl-slider
      - @featured_articles.each do |banner_item|
        div class="sl-slide" data-orientation=cycle('horizontal', 'vertical') data-slice1-rotation=rand(5..15) data-slice2-rotation=rand(5..15) data-slice1-scale=rand(1..3) data-slice2-scale=rand(1..3)

          .sl-slide-inner
            div class="bg-img bg-img-#{ banner_item.id }" style="background-image: url('#{ banner_item.avatar.url(:banner)}')"
            #item-description
              h2
                = banner_item.name
              p
                = banner_item.short_description
              = link_to 'Дізнатись більше!', article_path(banner_item), :class => 'button'
  nav#nav-dots.nav-dots
    - for i in 0...@featured_articles.count
      span.nav-dot class=("nav-dot-current" if i == 0)

app/views/partials/_article_home.html.slim
#articles-wrapper.f-height.page-indent
  .row.page-row
    .columns
      .section-title.articles-title
        | Статті

    - @last_article.each do |article|
      = render "article", article: article

app/views/partials/_banner_home.html.slim
#home-slider-wrapper
  .row.page-row
    .columns
      #home-slider
        - @banners.each do |banner|
          .slide style="background-image: url('#{banner.banner.url(:main)}')"
            span.title
              = banner.name
            = link_to(image_tag(banner.banner.url(:main)), banner.url, :title => banner.name)

app/views/partials/_catalog_home.html.slim
.shadow-top
#catalog-wrapper.f-height.page-indent.row.home-catalog-wrapper
  - @home_categories.each do |category|
    .columns.medium-6.large-4.category-column
      .catalog-category
        a href=category.url
          = category.name


.shadow-bottom

app/views/partials/_catalog_home0.html.erb
<!-- Shadow area -->
  <div class="shadow-top"></div>
  <!-- /Shadow area -->
  <!-- Catalog area -->
  <div id="catalog-wrapper" class="f-height page-indent">
    <div class="catalog-block g4 alpha">
        <%# cache do %>
        <%# get_left_catalogs.catalogs.each do |catalog_first_section| %>
        <div class="catalog-item"  data-category-name="<%#= catalog_first_section.slug %>" data-category-id="<%#= catalog_first_section.id %>">
          <a class="catalog-show-more animate" id="main-cat-1">Сухі суміші<span data-opened="false" id="status-1">+</span></a>
          <ul class="catalog-menu" id="menu-cat-1">
            <%# catalog_first_section.parent_catalogs.each do |parent_first_section| %>
            <!--li><%#= link_to parent_first_section.name, catalog_main_path+'/'+catalog_first_section.slug+'/'+parent_first_section.slug %></li -->
            <li><a href="/c/suhi-sumishi/shpaklivki-suhi">Шпаклівки сухі</a></li>
            <li><a href="/c/suhi-sumishi/shpaklivki-gotovi">Шпаклівки готові</a></li>
            <li><a href="/c/suhi-sumishi/suputni-materiali">Супутні матеріали</a></li>
            <li><a href="/c/suhi-sumishi/kleyuchi-sumishi">Клеючі суміші</a></li>
            <li><a href="/c/suhi-sumishi/zatirki-dlya-shviv">Затирки для швів</a></li>
            <li><a href="/c/suhi-sumishi/pidlogi">Підлоги</a></li>
            <%# end %>
          </ul>
        </div><!-- Catalog Item -->

      <div class="catalog-item"  data-category-name="<%#= catalog_first_section.slug %>" data-category-id="<%#= catalog_first_section.id %>">
        <a class="catalog-show-more animate" id="main-cat-2">Ізоляційні матеріали<span data-opened="false" id="status-2">+</span></a>
        <ul class="catalog-menu" id="menu-cat-2">
          <%# catalog_first_section.parent_catalogs.each do |parent_first_section| %>
          <!--li><%#= link_to parent_first_section.name, catalog_main_path+'/'+catalog_first_section.slug+'/'+parent_first_section.slug %></li -->
          <li><a href="/c/izolyatsiyni-materiali/bazaltova-vata">Базальтова вата</a></li>
          <li><a href="/c/izolyatsiyni-materiali/sklovata">Скловата</a></li>
          <li><a href="/c/izolyatsiyni-materiali/pinopolistirol">Пінополістирол</a></li>
          <%# end %>
        </ul>
      </div><!-- Catalog Item -->

      <div class="catalog-item"  data-category-name="<%#= catalog_first_section.slug %>" data-category-id="<%#= catalog_first_section.id %>">
        <a class="catalog-show-more animate" id="main-cat-3">Оздоблювальні матеріали<span data-opened="false" id="status-3">+</span></a>
        <ul class="catalog-menu" id="menu-cat-3">
          <%# catalog_first_section.parent_catalogs.each do |parent_first_section| %>
          <!--li><%#= link_to parent_first_section.name, catalog_main_path+'/'+catalog_first_section.slug+'/'+parent_first_section.slug %></li -->
          <li><a href="/c/ozdoblyuvalni-materiali/marmurova-krihta">Мармурова крихта</a></li>
          <li><a href="/c/ozdoblyuvalni-materiali/kasetoni-karnizi">Касетони, карнизи</a></li>
          <%# end %>
        </ul>
      </div><!-- Catalog Item -->
        <%# end %>
        <%# end %>
    </div><!-- Catalog wrap stuff -->

    <div class="catalog-block g4">
        <%# cache do %>
        <%# get_center_catalogs.catalogs.each do |catalog_middle_section| %>
          <div class="catalog-item"  data-category-name="<%#= catalog_middle_section.slug %>" data-category-id="<%#= catalog_middle_section.id %>">
            <a class="catalog-show-more animate" id="main-cat-4">Підвісні стелі<span data-opened="false" id="status-4">+</span></a>
            <ul class="catalog-menu" id="menu-cat-4">
              <%# catalog_middle_section.parent_catalogs.each do |parent_middle_section| %>
                <!--li><%#= link_to parent_middle_section.name, catalog_main_path+'/'+catalog_middle_section.slug+'/'+parent_middle_section.slug %></li -->
              <%# end %>
              <li><a href="/c/pidvisni-steli/komplektuyuchi">Комплектуючі</a></li>
              <li><a href="/c/pidvisni-steli/pliti-do-pidvisnih-stel">Плити до підвісних стель</a></li>
            </ul>
          </div><!-- Catalog Item -->

      <div class="catalog-item"  data-category-name="<%#= catalog_middle_section.slug %>" data-category-id="<%#= catalog_middle_section.id %>">
        <a class="catalog-show-more animate" id="main-cat-5">Грунтовки та захисні покриття<span data-opened="false" id="status-5">+</span></a>
        <ul class="catalog-menu" id="menu-cat-5">
          <%# catalog_middle_section.parent_catalogs.each do |parent_middle_section| %>
          <!--li><%#= link_to parent_middle_section.name, catalog_main_path+'/'+catalog_middle_section.slug+'/'+parent_middle_section.slug %></li -->
          <%# end %>
          <li><a href="/c/gruntovki-ta-zahisni-pokrittya/gruntovki">Грунтовки</a></li>
          <li><a href="/c/gruntovki-ta-zahisni-pokrittya/vogne-derevo-ta-biozahist">Вогне-, дерево- та біозахист</a></li>
        </ul>
      </div><!-- Catalog Item -->

      <div class="catalog-item"  data-category-name="<%#= catalog_middle_section.slug %>" data-category-id="<%#= catalog_middle_section.id %>">
        <a class="catalog-show-more animate" id="main-cat-6">Матеріали для будівництва<span data-opened="false" id="status-6">+</span></a>
        <ul class="catalog-menu" id="menu-cat-6">
          <%# catalog_middle_section.parent_catalogs.each do |parent_middle_section| %>
          <!--li><%#= link_to parent_middle_section.name, catalog_main_path+'/'+catalog_middle_section.slug+'/'+parent_middle_section.slug %></li -->
          <%# end %>
          <li><a href="/c/gruntovki-ta-zahisni-pokrittya/gruntovki">Основні будівельні матеріали</a></li>
        </ul>
      </div><!-- Catalog Item -->


        <%# end %>
        <%# end %>
    </div><!-- Catalog wrap stuff -->
    <div class="catalog-block g4 omega">
        <%# cache do %>
        <%# get_right_catalogs.catalogs.each do |catalog_last_section| %>
          <div class="catalog-item"  data-category-name="<%#= catalog_last_section.slug %>" data-category-id="<%#= catalog_last_section.id %>">
            <a class="catalog-show-more animate" id="main-cat-7">Гіпсокартонні системи<span data-opened="false" id="status-7">+</span></a>
            <ul class="catalog-menu" id="menu-cat-7">
              <%# catalog_last_section.parent_catalogs.each do |parent_last_section| %>
                <!--li><%#= link_to parent_last_section.name, catalog_main_path+'/'+catalog_last_section.slug+'/'+parent_last_section.slug %></li-->
              <%# end %>
              <li><a href="/c/gipsokartonni-sistemi/gipsokartonni-pliti">Гіпсокартонні плити</a></li>
              <li><a href="/c/gipsokartonni-sistemi/profili-dlya-gipsokartonnih-plit">Профілі для гіпсокартонних плит</a></li>
            </ul>
          </div><!-- Catalog Item -->

      <div class="catalog-item"  data-category-name="<%#= catalog_last_section.slug %>" data-category-id="<%#= catalog_last_section.id %>">
        <a class="catalog-show-more animate" id="main-cat-8">Лакофарбова продукція<span data-opened="false" id="status-8">+</span></a>
        <ul class="catalog-menu" id="menu-cat-8">
          <%# catalog_last_section.parent_catalogs.each do |parent_last_section| %>
          <!--li><%#= link_to parent_last_section.name, catalog_main_path+'/'+catalog_last_section.slug+'/'+parent_last_section.slug %></li-->
          <%# end %>
          <li><a href="/c/lakofarbova-produktsiya/osnovni-lakofarbovi-materiali">Основні лакофарбові матеріали</a></li>
        </ul>
      </div><!-- Catalog Item -->

      <div class="catalog-item"  data-category-name="<%#= catalog_last_section.slug %>" data-category-id="<%#= catalog_last_section.id %>">
        <a class="catalog-show-more animate" id="main-cat-9">Ущільнювачі та клеї<span data-opened="false" id="status-9">+</span></a>
        <ul class="catalog-menu" id="menu-cat-9">
          <%# catalog_last_section.parent_catalogs.each do |parent_last_section| %>
          <!--li><%#= link_to parent_last_section.name, catalog_main_path+'/'+catalog_last_section.slug+'/'+parent_last_section.slug %></li-->
          <%# end %>
          <li><a href="/c/uschilnyuvachi-ta-kleyi/pini">Піни</a></li>
          <li><a href="/c/uschilnyuvachi-ta-kleyi/germetiki">Герметики</a></li>
          <li><a href="/c/uschilnyuvachi-ta-kleyi/monazhni-kleyi">Монтажні клеї</a></li>
          <li><a href="/c/uschilnyuvachi-ta-kleyi/universalni-kleyi">Універсальні клеї</a></li>
          <li><a href="/c/uschilnyuvachi-ta-kleyi/stolyarni-kleyi">Столярні клеї</a></li>
        </ul>
      </div><!-- Catalog Item -->
        <%# end %>
        <%# end %>
    </div><!-- Catalog wrap stuff -->
  </div>
  <!-- /Catalog area -->
  <!-- Shadow area -->
  <div class="shadow-bottom"></div>
  <!-- /Shadow area -->

app/views/partials/_catalog_navigation.html.erb
<div class="catalog-navigation">
<% if current_page?(catalog_main_path) %>
  <% fetch_all_catalog.each do |catalog_section| %>
    <div class="catalog-item"  data-category-name="<%= catalog_section.slug %>" data-category-id="<%= catalog_section.id %>">
      <a class="catalog-show-more animate" id="main-cat-<%= catalog_section.id %>"><%= catalog_section.name %><span data-opened="false" id="status-<%= catalog_section.id %>">+</span></a>
      <ul class="catalog-menu" id="menu-cat-<%= catalog_section.id %>">
        <% catalog_section.parent_catalogs.each do |parent_section| %>
          <li><%= link_to parent_section.name, catalog_main_path+'/'+catalog_section.slug+'/'+parent_section.slug, :title => parent_section.name %><!-- span>+</span --></li>
        <% end %>
      </ul>
    </div><!-- Catalog Item -->
  <% end %>

<% elsif current_page?(parent_show_path) || current_page?(child_show_path) %>
  <% fetch_all_catalog.each do |catalog_section| %>
    <div class="catalog-item"  data-category-name="<%= catalog_section.slug %>" data-category-id="<%= catalog_section.id %>">
      <a class="catalog-show-more animate" id="main-cat-<%= catalog_section.id %>"><%= catalog_section.name %><span data-opened="false" id="status-<%= catalog_section.id %>"><% if catalog_section.id == @parent_catalog.catalog_id %>-<% else %>+<% end %></span></a>
      <ul class="catalog-menu <% if catalog_section.id == @parent_catalog.catalog_id %> visited <% end %>" id="menu-cat-<%= catalog_section.id %>">
        <% catalog_section.parent_catalogs.each do |parent_section| %>
          <% if parent_section.id == @parent_catalog.id %>
            <li><%= parent_section.name %><span data-opened="false" id="sub-status-<%= parent_section.id %>" class="sub-menu-status">+</span>
              <% if parent_section.child_catalogs.present? %>
                <script type="text/javascript" charset="utf-8">
                  $(document).ready(function() {
                    $("#sub-status-<%= @parent_catalog.id %>").text("-");
                    $('.sub-status-ul-<%= @parent_catalog.id %>').show();
                    $("#sub-status-<%= parent_section.id %>").click(function(){
                      $('.sub-status-ul-<%= parent_section.id %>').slideToggle('slow', function() {
                        // Animation complete.
                      });
                      $(this).each(function (i) {
                        if($(this).text() != "-"){
                          $(this).text("-");
                        }else{
                          $(this).text("+");
                        }
                      });
                    });
                  });
                </script>
                <ul class="sub-status-ul-<%= parent_section.id %>">
                  <% parent_section.child_catalogs.each do |child_li| %>
                    <% link_child = catalog_main_path+'/'+catalog_section.slug+'/'+@parent_catalog.slug+'/'+child_li.slug %>
                    <li><%= link_to child_li.name, link_child, :class => 'sub-'+child_li.slug, :title => child_li.name %></li>
                  <% end %>
                </ul>
              <% end %>
            </li>
          <% else %>
            <% if parent_section.child_catalogs.present? %>
              <script type="text/javascript" charset="utf-8">
                $(document).ready(function() {
                  $("#sub-status-<%= parent_section.id %>").click(function(){
                    $('.sub-status-ul-<%= parent_section.id %>').slideToggle('slow', function() {
                      // Animation complete.
                    });
                    $(this).each(function (i) {
                      if($(this).text() != "-"){
                        $(this).text("-");
                      }else{
                        $(this).text("+");
                      }
                    });
                  });
                });
              </script>
              <% link_parent = catalog_main_path+'/'+catalog_section.slug+'/'+parent_section.slug %>
              <li><%= link_to parent_section.name, link_parent, :title => parent_section.name %><% if count_childs(@parent_catalog.id) > 0 %><span class="sub-menu-status" data-opened="false" id="sub-status-<%= parent_section.id %>">+</span>
                  <ul class="sub-status-ul-<%= parent_section.id %>">
                    <% parent_section.child_catalogs.each do |child_li_next| %>
                      <li><%= link_to child_li_next.name, catalog_main_url+'/'+catalog_section.slug+'/'+parent_section.slug+'/'+child_li_next.slug, :class => 'sub-'+child_li_next.slug, :title => child_li_next.name %></li>
                    <% end %>
                  </ul>
                <% end %>
              </li>
            <% else %>
              <% link_parent = catalog_main_path+'/'+catalog_section.slug+'/'+parent_section.slug %>
              <li><%= link_to parent_section.name, link_parent, :title => parent_section.name %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div><!-- Catalog Item -->
  <% end %>
<% elsif current_page?(product_show_path) %> <!-- Product render part -->
  <% fetch_all_catalog.each do |catalog_section| %>
    <%#= catalog_section.inspect %>
    <div class="catalog-item"  data-category-name="<%= catalog_section.slug %>" data-category-id="<%= catalog_section.id %>">
      <a class="catalog-show-more animate" id="main-cat-<%= catalog_section.id %>"><%= catalog_section.name %><span data-opened="false" id="status-<%= catalog_section.id %>"><% if catalog_section.id == parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).catalog_id %>-<% else %>+<% end %></span></a>
      <ul class="catalog-menu <% if catalog_section.id == parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).catalog_id %> visited <% end %>" id="menu-cat-<%= catalog_section.id %>">
        <% catalog_section.parent_catalogs.each do |parent_section| %>
          <% if parent_section.id == parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).id %>
            <li><%= parent_section.name %><span data-opened="false" id="sub-status-<%= parent_section.id %>" class="sub-menu-status">+</span>
              <% if parent_section.child_catalogs.present? %>
                <script type="text/javascript" charset="utf-8">
                  $(document).ready(function() {
                    $('.sub-status-ul-<%= parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).id %>').show();
                    $("#sub-status-<%= parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).id %>").text("-");
                    $("#sub-status-<%= parent_section.id %>").click(function(){
                      $('.sub-status-ul-<%= parent_section.id %>').slideToggle('slow', function() {
                        // Animation complete.
                      });
                      $(this).each(function (i) {
                        if($(this).text() != "-"){
                          $(this).text("-");
                        }else{
                          $(this).text("+");
                        }
                      });
                    });
                  });
                </script>
                <ul class="sub-status-ul-<%= parent_section.id %>">
                  <% parent_section.child_catalogs.each do |child_li| %>
                    <li><%= link_to child_li.name, catalog_main_url+'/'+catalog_section.slug+'/'+parent_section.slug+'/'+child_li.slug, :class => 'sub-'+child_li.slug, :title => child_li.name %></li>
                  <% end %>
                </ul>
              <% end %>
            </li>
          <% else %>
            <% if parent_section.child_catalogs.present? %>
              <script type="text/javascript" charset="utf-8">
                $(document).ready(function() {
                  $('.sub-status-ul-<%= parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).id %>').show();
                  $("#sub-status-<%= parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).id %>").text("-");
                  $("#sub-status-<%= parent_section.id %>").click(function(){
                    $('.sub-status-ul-<%= parent_section.id %>').slideToggle('slow', function() {
                      // Animation complete.
                    });
                    $(this).each(function (i) {
                      if($(this).text() != "-"){
                        $(this).text("-");
                      }else{
                        $(this).text("+");
                      }
                    });
                  });
                });
              </script>
              <li><%= link_to parent_section.name, catalog_main_url+'/'+catalog_section.slug+'/'+parent_section.slug, :title => parent_section.name %><% if count_childs(parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).id) > 0 %><span class="sub-menu-status" data-opened="false" id="sub-status-<%= parent_section.id %>">+</span>
                  <ul class="sub-status-ul-<%= parent_section.id %>">
                    <% parent_section.child_catalogs.each do |child_li_next| %>
                      <li><%= link_to child_li_next.name, catalog_main_url+'/'+catalog_section.slug+'/'+parent_section.slug+'/'+child_li_next.slug, :class => 'sub-'+child_li_next.slug, :title => child_li_next.name %></li>
                    <% end %>
                  </ul>
                <% end %>
              </li>
            <% else %>
              <li><%= link_to parent_section.name, catalog_main_url+'/'+catalog_section.slug+'/'+parent_section.slug, :title => parent_section.name %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div><!-- Catalog Item -->
  <% end %>
<% end %>
</div>

app/views/partials/_footer.html.slim
#footer-wrapper.f-height.container.page-indent
  .row.page-row
    .columns.large-4.contact-info-row.omega.contacts
      img.footer-block-header-icon src=asset_path("h-img.png") style="position: absolute; left: -35px;"
      .block-title Контакти:
      p#office.footer-title
        | офіс:
        a.tel href=office_phone_url style="" title=office_phone
          = office_phone
      p#sale.footer-title
        | продаж:
        a.tel href=main_site_phone_url style="" title=main_site_phone
          = main_site_phone
      p#sale.footer-title
        | продаж:
        a.tel href=sales_phone_url style="" title=sales_phone
          = sales_phone
      p.sub-title
        a href=contacts_path  Більш детальна контактна інформація
    .columns.large-4.contact-info-row.work
      img.footer-block-header-icon src=asset_path("h-img.png") style=("position: absolute; left: -35px;")
      .block-title Графік роботи:
      p#pn-pt.footer-title
        | Пн — Пт:
        span.me-color style=""  09:00 — 18:00
      p#sb.footer-title
        | Сб:
        span.me-color.me2 style=""  09:00 — 14:00
      p.sub-title На складі обід з 13:00 до 14:00
    .columns.large-4.alpha.contact-info-row.copyright id=("contact-info-row copyright")
      .inner
        p.copyrights © 2012 — #{Date.today.year} ТзОВ «Десятка»
        #developed-by
          a href="http://voroninstudio.eu"
            img alt="" src=asset_path("/assets/v-logo.png")
          p.title
            br
            | Зроблено
            a href="http://voroninstudio.eu"  дизайн студією М. Вороніна
            |&thinsp; в 2013 році.

app/views/partials/_gmap.html.slim
script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=#{ ENV["GOOGLE_MAPS_API_KEY"] }"
#gmap-wrapper.container.f-height
  .columns
    h2.title
      = image_tag('h-img.png')
      | Ми на Google карті:
  #map-container.columns
    #map

app/views/partials/_header.html.slim
#header.header.page-indent
  .row.page-row
    #logo.columns.small-3
      .image-container
        - if current_page?(root_path)
          = image_tag('logo.png', :alt => '')
          = image_tag "logo-big.jpg", class: "rect-logo"
        - else
          = link_to(image_tag('logo.png', :alt => ''), root_path)
          = link_to(image_tag('logo-big.jpg', :alt => '', class: "rect-logo"), root_path)

    .mobile-menu-button
      img src=asset_path("mobile-menu-button.png") alt="show menu"
    #menu.columns.large-9
      = render "partials/menu"

app/views/partials/_menu.html.slim
nav
  ul.header-nav
    - main_menu.each do |item_key, item|
      li class="menu-item-#{item_key}" class=("active" if item[:active]) class=("has-active" if item[:has_active])

        - if !item[:active]
          a.menu-item href=item[:url] title=item[:title]
            = item[:name]
        - else
          span.menu-item title=item[:title]
            = item[:name]


        - if item_key == "catalog"
          .main-menu-catalog-menu
            = render "catalog/catalog_menu"

app/views/partials/_prod_breadcrumbs.html.erb
<div id="product-breadcrumbs" class="g12 pd-me">
  <ul>
    <li><span>//</span><%= link_to 'Головна', root_path, :title => 'Головна' %></li>
    <li><span>/</span><%= link_to 'Каталог', catalog_main_path, :title => 'Каталог' %></li>
    <li><span>/</span><%= link_to catalog_name_breadcrumb(parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id))).name, catalog_show_path(catalog_name_breadcrumb(parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)))), :title => catalog_name_breadcrumb(parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id))).name %></li>
    <li><span>/</span><%= link_to parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).name, parent_show_path(parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id))), :title => parent_name_breadcrumb(child_name_breadcrumb(@product.child_catalog_id)).name %></li>
    <li><span>/</span><%= link_to child_name_breadcrumb(@product.child_catalog_id).name, child_show_path(child_name_breadcrumb(@product.child_catalog_id)), :title => child_name_breadcrumb(@product.child_catalog_id).name %></li>
    <li><span>/</span><%= @product.name %></li>
  </ul>
</div>

app/views/partials/_sponsor_all.html.slim
.shadow-top
#sponsor-parent.page-indent
  #sponsor-wrapper.container
    - fetch_sponsors.each do |sponsor_item|
      .columns.small-6.medium-4.large-2.sponsor-item
        = link_to( image_tag(sponsor_item.sponsor.url, :alt => sponsor_item.description, :style => ''), sponsor_item.link )
.shadow-bottom

app/views/partials/_unsupported_browsers.html.slim
#unsupported-browsers.f-height